import { 
  collection, 
  doc, 
  getDocs, 
  getDoc,
  addDoc, 
  updateDoc, 
  query, 
  where, 
  orderBy,
  Timestamp,
  onSnapshot,
  arrayUnion
} from 'firebase/firestore';
import { z } from 'zod';
import { db } from '@/lib/firebase';
import { Appointment } from '@/types/appointments';

const APPOINTMENTS_COLLECTION = 'appointments';

// Input validation schemas
const appointmentInputSchema = z.object({
  providerId: z.string().min(1, 'Provider ID required'),
  providerName: z.string().trim().min(1, 'Provider name required').max(200),
  patientName: z.string().trim().min(2, 'Name must be at least 2 characters').max(100),
  patientPhone: z.string().trim().min(8, 'Phone must be at least 8 characters').max(20),
  patientEmail: z.string().email('Invalid email').max(255).optional().or(z.literal('')),
  patientId: z.string().min(1, 'Patient ID required'),
  dateTime: z.string().refine((val) => !isNaN(Date.parse(val)), 'Invalid date format'),
  notes: z.string().max(500, 'Notes too long').optional(),
  urgency: z.enum(['urgent', 'routine']).optional(),
});

const statusSchema = z.enum(['pending', 'confirmed', 'cancelled', 'completed']);

// Helper to convert Firestore doc to Appointment
const docToAppointment = (docSnap: any): Appointment => {
  const data = docSnap.data();
  return {
    id: docSnap.id,
    providerId: data.providerId,
    providerName: data.providerName,
    patientName: data.patientName,
    patientPhone: data.patientPhone,
    patientEmail: data.patientEmail,
    patientId: data.patientId,
    dateTime: data.dateTime?.toDate?.()?.toISOString() || data.dateTime,
    status: data.status || 'pending',
    urgency: data.urgency || 'routine',
    notes: data.notes,
    rescheduleHistory: data.rescheduleHistory || [],
    createdAt: data.createdAt?.toDate?.()?.toISOString() || data.createdAt,
    updatedAt: data.updatedAt?.toDate?.()?.toISOString() || data.updatedAt
  };
};

// Create a new appointment
export const createAppointment = async (
  appointment: Omit<Appointment, 'id' | 'createdAt' | 'updatedAt'>
): Promise<string> => {
  // Validate input
  const validationResult = appointmentInputSchema.safeParse(appointment);
  if (!validationResult.success) {
    throw new Error(validationResult.error.errors[0]?.message || 'Invalid appointment data');
  }

  const validatedData = validationResult.data;
  const now = Timestamp.now();
  
  // Validate date is not in the past
  const appointmentDate = new Date(validatedData.dateTime);
  if (appointmentDate < new Date()) {
    throw new Error('Cannot book appointments in the past');
  }
  
  // Validate not on Sunday (day 0)
  if (appointmentDate.getDay() === 0) {
    throw new Error('Cannot book appointments on Sundays');
  }
  
  // Extract user ID from provider ID (format: provider_{userId})
  const providerUserId = validatedData.providerId.replace(/^provider_/, '');
  
  // Remove undefined fields — Firestore rejects them
  const docData: Record<string, any> = {
    providerId: validatedData.providerId,
    providerName: validatedData.providerName,
    patientName: validatedData.patientName,
    patientPhone: validatedData.patientPhone,
    patientId: validatedData.patientId,
    urgency: validatedData.urgency || 'routine',
    providerUserId,
    dateTime: Timestamp.fromDate(appointmentDate),
    status: 'pending',
    rescheduleHistory: [],
    createdAt: now,
    updatedAt: now,
  };
  if (validatedData.patientEmail) docData.patientEmail = validatedData.patientEmail;
  if (validatedData.notes) docData.notes = validatedData.notes;

  const docRef = await addDoc(collection(db, APPOINTMENTS_COLLECTION), docData);
  
  // Auto-create first note in subcollection if booking has notes/reason
  if (validatedData.notes) {
    try {
      await addDoc(collection(db, APPOINTMENTS_COLLECTION, docRef.id, 'notes'), {
        senderName: validatedData.patientName,
        senderRole: 'patient',
        senderId: validatedData.patientId,
        content: `Motif: ${validatedData.notes}`,
        isAutoGenerated: true,
        createdAt: Timestamp.now(),
      });
    } catch (e) {
      console.error('Failed to auto-create first note:', e);
    }
  }
  
  return docRef.id;
};

// Get appointments by patient ID
export const getAppointmentsByPatient = async (patientId: string): Promise<Appointment[]> => {
  try {
    const q = query(
      collection(db, APPOINTMENTS_COLLECTION),
      where('patientId', '==', patientId),
      orderBy('dateTime', 'desc')
    );
    
    const snapshot = await getDocs(q);
    return snapshot.docs.map(docToAppointment);
  } catch {
    return [];
  }
};

// Get appointments by provider's auth UID
export const getAppointmentsByProvider = async (providerUserId: string): Promise<Appointment[]> => {
  try {
    const q = query(
      collection(db, APPOINTMENTS_COLLECTION),
      where('providerUserId', '==', providerUserId),
      orderBy('dateTime', 'desc')
    );
    
    const snapshot = await getDocs(q);
    return snapshot.docs.map(docToAppointment);
  } catch {
    return [];
  }
};

// Update appointment status
export const updateAppointmentStatus = async (
  id: string, 
  status: Appointment['status']
): Promise<void> => {
  const docRef = doc(db, APPOINTMENTS_COLLECTION, id);
  await updateDoc(docRef, {
    status,
    updatedAt: Timestamp.now()
  });
};

// Cancel an appointment
export const cancelAppointment = async (id: string): Promise<void> => {
  return updateAppointmentStatus(id, 'cancelled');
};

// Confirm an appointment (provider action)
export const confirmAppointment = async (id: string): Promise<void> => {
  return updateAppointmentStatus(id, 'confirmed');
};

// Complete an appointment (provider action)
export const completeAppointment = async (id: string): Promise<void> => {
  return updateAppointmentStatus(id, 'completed');
};

// Reschedule an appointment (provider action)
export const rescheduleAppointment = async (
  id: string,
  newDateTime: string,
  rescheduledBy: string
): Promise<void> => {
  const docRef = doc(db, APPOINTMENTS_COLLECTION, id);
  const docSnap = await getDoc(docRef);
  if (!docSnap.exists()) throw new Error('Appointment not found');
  
  const data = docSnap.data();
  const oldDateTime = data.dateTime?.toDate?.()?.toISOString() || data.dateTime;
  const newDate = new Date(newDateTime);
  
  if (newDate < new Date()) throw new Error('Cannot reschedule to a past date');
  if (newDate.getDay() === 0) throw new Error('Cannot reschedule to Sunday');
  
  await updateDoc(docRef, {
    dateTime: Timestamp.fromDate(newDate),
    status: 'confirmed',
    updatedAt: Timestamp.now(),
    rescheduleHistory: arrayUnion({
      from: oldDateTime,
      to: newDate.toISOString(),
      by: rescheduledBy,
      at: new Date().toISOString(),
    }),
  });
};

// Subscribe to real-time appointment updates for a patient
// Falls back to simpler query if composite index is missing
export const subscribeToPatientAppointments = (
  patientId: string,
  callback: (appointments: Appointment[]) => void,
  onError?: (error: Error) => void
): (() => void) => {
  let unsubscribe: (() => void) | null = null;

  const sortAndDeliver = (snapshot: any) => {
    const appointments = snapshot.docs.map(docToAppointment);
    appointments.sort((a: Appointment, b: Appointment) =>
      new Date(b.dateTime).getTime() - new Date(a.dateTime).getTime()
    );
    callback(appointments);
  };

  const indexedQ = query(
    collection(db, APPOINTMENTS_COLLECTION),
    where('patientId', '==', patientId),
    orderBy('dateTime', 'desc')
  );

  unsubscribe = onSnapshot(indexedQ, sortAndDeliver, (error) => {
    console.warn('Patient indexed query failed, using fallback:', error.message);
    const fallbackQ = query(
      collection(db, APPOINTMENTS_COLLECTION),
      where('patientId', '==', patientId)
    );
    unsubscribe = onSnapshot(fallbackQ, sortAndDeliver, (err) => {
      console.error('Fallback patient appointments error:', err);
      if (onError) onError(err);
      else callback([]);
    });
  });

  return () => {
    if (unsubscribe) unsubscribe();
  };
};

// Subscribe to real-time appointment updates for a provider (by auth UID)
// Falls back to a simpler query (no orderBy) if composite index is missing
export const subscribeToProviderAppointments = (
  providerUserId: string,
  callback: (appointments: Appointment[]) => void,
  onError?: (error: Error) => void
): (() => void) => {
  let unsubscribe: (() => void) | null = null;
  let usingFallback = false;

  const sortAndDeliver = (snapshot: any) => {
    const appointments = snapshot.docs.map(docToAppointment);
    // Sort client-side (desc) to guarantee order even without index
    appointments.sort((a: Appointment, b: Appointment) =>
      new Date(b.dateTime).getTime() - new Date(a.dateTime).getTime()
    );
    callback(appointments);
  };

  const subscribeFallback = () => {
    usingFallback = true;
    console.warn('Using fallback query without orderBy for provider appointments');
    const fallbackQ = query(
      collection(db, APPOINTMENTS_COLLECTION),
      where('providerUserId', '==', providerUserId)
    );
    unsubscribe = onSnapshot(fallbackQ, sortAndDeliver, (error) => {
      console.error('Fallback provider appointments error:', error);
      if (onError) onError(error);
      else callback([]);
    });
  };

  // Try the indexed query first
  const indexedQ = query(
    collection(db, APPOINTMENTS_COLLECTION),
    where('providerUserId', '==', providerUserId),
    orderBy('dateTime', 'desc')
  );

  unsubscribe = onSnapshot(indexedQ, sortAndDeliver, (error) => {
    console.warn('Indexed query failed, trying fallback:', error.message);
    // If index missing (code 9) or permission error, try fallback
    subscribeFallback();
  });

  return () => {
    if (unsubscribe) unsubscribe();
  };
};

// Get upcoming appointments count for a provider (this week) - uses auth UID
export const getUpcomingAppointmentsCount = async (providerUserId: string): Promise<number> => {
  const appointments = await getAppointmentsByProvider(providerUserId);
  const now = new Date();
  const weekFromNow = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
  
  return appointments.filter(apt => {
    const aptDate = new Date(apt.dateTime);
    return aptDate >= now && aptDate <= weekFromNow && apt.status !== 'cancelled';
  }).length;
};

// Get all appointments count for platform stats (admin)
export const getAllAppointmentsCount = async (): Promise<number> => {
  try {
    const snapshot = await getDocs(collection(db, APPOINTMENTS_COLLECTION));
    return snapshot.size;
  } catch {
    return 0;
  }
};

// Get booked slots for a specific provider on a specific date
export const getBookedSlotsForDate = async (
  providerId: string, 
  date: Date
): Promise<string[]> => {
  try {
    // Set date range for the entire day
    const startOfDay = new Date(date);
    startOfDay.setHours(0, 0, 0, 0);
    
    const endOfDay = new Date(date);
    endOfDay.setHours(23, 59, 59, 999);
    
    const q = query(
      collection(db, APPOINTMENTS_COLLECTION),
      where('providerId', '==', providerId),
      where('dateTime', '>=', Timestamp.fromDate(startOfDay)),
      where('dateTime', '<=', Timestamp.fromDate(endOfDay))
    );
    
    const snapshot = await getDocs(q);
    
    // Extract booked time slots (only non-cancelled appointments)
    const bookedSlots: string[] = [];
    snapshot.docs.forEach(doc => {
      const data = doc.data();
      if (data.status !== 'cancelled') {
        const dateTime = data.dateTime?.toDate?.() || new Date(data.dateTime);
        const hours = dateTime.getHours().toString().padStart(2, '0');
        const minutes = dateTime.getMinutes().toString().padStart(2, '0');
        bookedSlots.push(`${hours}:${minutes}`);
      }
    });
    
    return bookedSlots;
  } catch (error) {
    console.error('Error fetching booked slots:', error);
    return [];
  }
};

// Subscribe to real-time booked slots for a specific provider and date
export const subscribeToBookedSlots = (
  providerId: string,
  date: Date,
  callback: (bookedSlots: string[]) => void
): (() => void) => {
  const startOfDay = new Date(date);
  startOfDay.setHours(0, 0, 0, 0);
  
  const endOfDay = new Date(date);
  endOfDay.setHours(23, 59, 59, 999);
  
  const q = query(
    collection(db, APPOINTMENTS_COLLECTION),
    where('providerId', '==', providerId),
    where('dateTime', '>=', Timestamp.fromDate(startOfDay)),
    where('dateTime', '<=', Timestamp.fromDate(endOfDay))
  );
  
  return onSnapshot(q, (snapshot) => {
    const bookedSlots: string[] = [];
    snapshot.docs.forEach(doc => {
      const data = doc.data();
      if (data.status !== 'cancelled') {
        const dateTime = data.dateTime?.toDate?.() || new Date(data.dateTime);
        const hours = dateTime.getHours().toString().padStart(2, '0');
        const minutes = dateTime.getMinutes().toString().padStart(2, '0');
        bookedSlots.push(`${hours}:${minutes}`);
      }
    });
    callback(bookedSlots);
  }, (error) => {
    console.error('Error subscribing to booked slots:', error);
    callback([]);
  });
};

// Get available slots for a provider on a specific date based on their schedule
export interface AvailabilitySlot {
  time: string;
  status: 'available' | 'booked' | 'past';
}

export const getAvailabilityForDate = async (
  providerId: string,
  date: Date,
  schedule?: Record<string, { open: string; close: string; closed?: boolean } | undefined>
): Promise<AvailabilitySlot[]> => {
  // Default time slots (30-minute intervals from 8am to 6pm)
  const defaultSlots = [
    '08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30',
    '12:00', '12:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', 
    '17:00', '17:30'
  ];
  
  // Get booked slots
  const bookedSlots = await getBookedSlotsForDate(providerId, date);
  
  // Get current time for "past" status
  const now = new Date();
  const isToday = date.toDateString() === now.toDateString();
  
  // Generate slots based on provider schedule or defaults
  let availableTimeRange = { open: '08:00', close: '18:00' };
  
  if (schedule) {
    const dayNames = ['dimanche', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'];
    const daySchedule = schedule[dayNames[date.getDay()]];
    
    if (daySchedule && !daySchedule.closed) {
      availableTimeRange = { open: daySchedule.open, close: daySchedule.close };
    } else if (daySchedule?.closed) {
      return []; // Closed on this day
    }
  }
  
  // Filter slots within provider's working hours
  const slots: AvailabilitySlot[] = defaultSlots
    .filter(slot => {
      return slot >= availableTimeRange.open && slot < availableTimeRange.close;
    })
    .map(time => {
      // Check if slot is in the past
      if (isToday) {
        const [hours, minutes] = time.split(':').map(Number);
        const slotTime = new Date(date);
        slotTime.setHours(hours, minutes, 0, 0);
        
        if (slotTime <= now) {
          return { time, status: 'past' as const };
        }
      }
      
      // Check if slot is booked
      if (bookedSlots.includes(time)) {
        return { time, status: 'booked' as const };
      }
      
      return { time, status: 'available' as const };
    });
  
  return slots;
};

// Seed 2 demo appointments for visual testing
export const seedDemoAppointments = async (
  providerId: string,
  providerUserId: string,
  providerName: string
): Promise<void> => {
  const now = new Date();
  const today14 = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 14, 0, 0);
  const tomorrowDate = new Date(now);
  tomorrowDate.setDate(tomorrowDate.getDate() + 1);
  const tomorrow1030 = new Date(tomorrowDate.getFullYear(), tomorrowDate.getMonth(), tomorrowDate.getDate(), 10, 30, 0);

  const demos = [
    {
      providerId,
      providerUserId,
      providerName,
      patientName: 'Karim Benali',
      patientPhone: '0550112233',
      patientEmail: '',
      patientId: 'demo-patient-karim',
      dateTime: Timestamp.fromDate(today14),
      notes: 'Consultation générale',
      urgency: 'routine',
      status: 'confirmed',
      rescheduleHistory: [],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
    },
    {
      providerId,
      providerUserId,
      providerName,
      patientName: 'Sara Haddad',
      patientPhone: '0661223344',
      patientEmail: '',
      patientId: 'demo-patient-sara',
      dateTime: Timestamp.fromDate(tomorrow1030),
      notes: 'Douleur thoracique',
      urgency: 'urgent',
      status: 'pending',
      rescheduleHistory: [],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
    },
  ];

  for (const demo of demos) {
    await addDoc(collection(db, APPOINTMENTS_COLLECTION), demo);
  }
};
