import {
  collection,
  addDoc,
  getDocs,
  query,
  orderBy,
  onSnapshot,
  Timestamp,
} from 'firebase/firestore';
import { z } from 'zod';
import { db } from '@/lib/firebase';
import { AppointmentNote } from '@/types/appointmentNotes';

const MAX_NOTES = 10;
const MAX_CONTENT_LENGTH = 1000;

const noteInputSchema = z.object({
  senderName: z.string().min(1).max(100),
  senderRole: z.enum(['patient', 'provider']),
  senderId: z.string().min(1),
  content: z.string().min(1, 'Le message ne peut pas être vide').max(MAX_CONTENT_LENGTH, `Maximum ${MAX_CONTENT_LENGTH} caractères`),
  isAutoGenerated: z.boolean().optional(),
});

const docToNote = (docSnap: any, appointmentId: string): AppointmentNote => {
  const data = docSnap.data();
  return {
    id: docSnap.id,
    appointmentId,
    senderName: data.senderName,
    senderRole: data.senderRole,
    senderId: data.senderId,
    content: data.content,
    createdAt: data.createdAt?.toDate?.()?.toISOString() || data.createdAt,
    isAutoGenerated: data.isAutoGenerated || false,
  };
};

function notesCollection(appointmentId: string) {
  return collection(db, 'appointments', appointmentId, 'notes');
}

export const getNotesForAppointment = async (appointmentId: string): Promise<AppointmentNote[]> => {
  const q = query(notesCollection(appointmentId), orderBy('createdAt', 'asc'));
  const snapshot = await getDocs(q);
  return snapshot.docs.map(d => docToNote(d, appointmentId));
};

export const getNoteCount = async (appointmentId: string): Promise<number> => {
  const snapshot = await getDocs(notesCollection(appointmentId));
  return snapshot.size;
};

export const addNoteToAppointment = async (
  appointmentId: string,
  note: z.infer<typeof noteInputSchema>
): Promise<string> => {
  const validated = noteInputSchema.parse(note);

  const docRef = await addDoc(notesCollection(appointmentId), {
    senderName: validated.senderName,
    senderRole: validated.senderRole,
    senderId: validated.senderId,
    content: validated.content,
    isAutoGenerated: validated.isAutoGenerated || false,
    createdAt: Timestamp.now(),
  });

  return docRef.id;
};

export const subscribeToNotes = (
  appointmentId: string,
  callback: (notes: AppointmentNote[]) => void
): (() => void) => {
  let fallbackUnsub: (() => void) | null = null;

  const q = query(notesCollection(appointmentId), orderBy('createdAt', 'asc'));
  const primaryUnsub = onSnapshot(
    q,
    (snapshot) => {
      callback(snapshot.docs.map(d => docToNote(d, appointmentId)));
    },
    (error) => {
      console.warn('Notes subscription error (may need to deploy Firestore rules):', error.message);

      // Try fallback without orderBy
      const fallbackQ = query(notesCollection(appointmentId));
      fallbackUnsub = onSnapshot(
        fallbackQ,
        (snap) => {
          const notes = snap.docs.map(d => docToNote(d, appointmentId));
          notes.sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());
          callback(notes);
        },
        (fallbackError) => {
          console.warn('Notes fallback also failed:', fallbackError.message);
          // Return empty notes - rules likely not deployed yet
          callback([]);
        }
      );
    }
  );

  return () => {
    primaryUnsub();
    fallbackUnsub?.();
  };
};
