import { useState, useEffect, useCallback, useRef } from 'react';
import { AppointmentNote } from '@/types/appointmentNotes';
import { subscribeToNotes, addNoteToAppointment } from '@/services/appointmentNotesService';

export function useAppointmentNotes(
  appointmentId: string | null,
  onNewNote?: (note: AppointmentNote) => void
) {
  const [notes, setNotes] = useState<AppointmentNote[]>([]);
  const [loading, setLoading] = useState(true);
  const prevIdsRef = useRef<Set<string>>(new Set());
  const isFirstSnapshot = useRef(true);

  useEffect(() => {
    if (!appointmentId) {
      setNotes([]);
      setLoading(false);
      prevIdsRef.current = new Set();
      isFirstSnapshot.current = true;
      return;
    }
    setLoading(true);
    isFirstSnapshot.current = true;

    const unsub = subscribeToNotes(appointmentId, (newNotes) => {
      if (isFirstSnapshot.current) {
        // First load: seed the ref, no callbacks
        prevIdsRef.current = new Set(newNotes.map(n => n.id));
        isFirstSnapshot.current = false;
      } else if (onNewNote) {
        // Detect truly new notes
        newNotes.forEach(n => {
          if (!prevIdsRef.current.has(n.id)) {
            onNewNote(n);
          }
        });
        prevIdsRef.current = new Set(newNotes.map(n => n.id));
      }
      setNotes(newNotes);
      setLoading(false);
    });
    return unsub;
  }, [appointmentId, onNewNote]);

  return { notes, loading };
}

export function useAddNote() {
  const [isPending, setIsPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const addNote = useCallback(async (
    appointmentId: string,
    note: {
      senderName: string;
      senderRole: 'patient' | 'provider';
      senderId: string;
      content: string;
      isAutoGenerated?: boolean;
    }
  ) => {
    setIsPending(true);
    setError(null);
    try {
      await addNoteToAppointment(appointmentId, note);
    } catch (e: any) {
      setError(e.message || 'Erreur');
      throw e;
    } finally {
      setIsPending(false);
    }
  }, []);

  return { addNote, isPending, error };
}
