export interface AppointmentNote {
  id: string;
  appointmentId: string;
  senderName: string;
  senderRole: 'patient' | 'provider';
  senderId: string;
  content: string;
  createdAt: string;
  isAutoGenerated: boolean;
}
